test_that("arithmetic - bad inputs", {
  expect_error(arithmetic("5.5", 1.2))
  expect_error(arithmetic(NA, 1.2))
  expect_error(arithmetic(5.5, "1.2"))
  expect_error(arithmetic(5.5, -1.2))
  expect_error(arithmetic(5, NA))
  expect_error(arithmetic(5.5, 1.2, n_left = -3))
  expect_error(arithmetic(5.5, 1.2, n_left = "3"))
  expect_error(arithmetic(5.5, 1.2, n_left = NA))
  expect_error(arithmetic(5.5, 1.2, n_right = -3))
  expect_error(arithmetic(5.5, 1.2, n_right = NA))
  expect_error(arithmetic(5.5, 1.2, n_right = "3"))
})
